### ISSUE TITLE
Recieving error for missing module.

### ISSUE THREAD

**Issue by mtahsin26** [nickb1080/nba#40]
You might need to update your package.json to include the node-fetch module. Here is the error I received after installing and trying to run the example code from the readme

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at createGetJson (/{PROJECT_PATH}/node_modules/nba/lib/get-json.js:24:15)
    at Object.<anonymous> (/{PROJECT_PATH}/node_modules/nba/lib/get-json.js:63:50)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by nickb1080** [comment]
Geez, you're right. I have no idea how it passed CI without that. Thanks for pointing it out. Fixed in `3.2.6`.
